# utils/config.py

DATA_PATH = "data/processed/app_dataset.csv"
BASE_PATH = "data/interim/data_clean.parquet"

VARS_CLUSTER = [
    "rotacion_stocks",
    "productividad_ventas_pax",
    "productividad_va_pax",
    "inmovilizado_empleado",
]

LABELS = {
    "rotacion_stocks": "Rotación de stocks",
    "productividad_ventas_pax": "Productividad ventas/pax",
    "margen": "Margen",
    "nofs_ventas": "NOFs / Ventas",
    "productividad_va_pax": "Productividad VA/pax",
    "inmovilizado_empleado": "Inmovilizado/empleado",
    "ebitda_porc": "EBITDA (%)",
    "ingresos_de_explotacion": "Ingresos de explotación",
    "competitividad": "Competitividad",
    "resultado_del_ejercicio": "Resultado del ejercicio",
    "resultado_explotacion": "Resultado de explotación",
    "ebitda": "EBITDA",
    "cash_flow": "Cash flow",
    "personal_porcentaje": "Personal (%)",
    "total_activo": "Total activo",
    "fondos_propios": "Fondos propios",
    "fondo_de_maniobra": "Fondo de maniobra",
    "existencias": "Existencias",
    "materiales": "Materiales",
    "inmovilizado": "Inmovilizado",
    "rotacion_de_activos": "Rotación de activos",
    "deudores": "Deudores",
    "deudores_sin_iva": "Deudores sin IVA",
    "ingresos_de_explotacion_mil_eur_ano_1": "Ingresos de explotación año -1",
    "ingresos_de_explotacion_mil_eur_ano_2": "Ingresos de explotación año -2",
    "dotaciones_para_amortiz_de_inmovil": "Dotaciones para amortización de inmovil.",
    "valor_agregado": "Valor agregado",
    "rendimiento": "Rendimiento",
    "acreedores_comerciales": "Acreedores comerciales",
    "acreedores_comerciales_sin_iva": "Acreedores comerciales sin IVA",
    "gastos_de_personal": "Gastos de personal",
    "numero_empleados": "Nº de empleados",
    "coste": "Coste",
    "coste_por_persona": "Coste por persona",
    "deudas_financieras": "Deudas financieras",
    "exportacion_euros": "Exportación en euros",
    "va_porcentaje": "VA (%)",
    "exportacion_percent": "Exportación (%)",
    "crecimiento": "Crecimiento",
    "numero_de_participadas": "Nº de participadas",
    "antiguedad": "Antiguedad",
    "no_of_companies_in_corporate_group": "Nº compañías en grupo corporativo",
    "clientes_proveedores_sin_iva": "Clientes/proveedores sin IVA",
    "importacion_euros": "Importación en euros",
    "capitalizacion": "Capitalización",
    "importacion_percent": "Importación (%)",
    "inmovilizado_percent": "Inmovilizado (%)",
    "inmovilizado_tactivo": "Inmovilizado/T.activo",
    "remuneracion_consejo": "Remuneración consejo",
    "segmentacion_tamano_1_grp": "Segmentación tamaño 1",
    "segmentacion_tamano_2_grp": "Segmentación tamaño 2",
    "auditor_sn": "Auditor sí/no",
    "importador_exportador": "Importador/exportador",
    "marca_sn": "Marca sí/no",
    "sector": "Sector",
    "sector_grp": "Sector agrupado",
    "crece": "Crecimiento",
    "participadas": "Participadas",
    "consejo": "Consejo",
    "grupos_corporativos": "Grupos corporativos",
    "segmentacion_de_antiguedad": "Segmentación de antigüedad",
    "localidad": "Localidad",
    "localidad_grp": "Localidad agrupada",
}

EXCLUDE_VARS = {
    "actividad",
    "literal_codigo_cnae_2009_primario",
    "nombre_auditor",
    "nombre_marca",
    "año",
    "codigo_primario_cnae_2009",
    "id",
    "ult_año_disp",
    "segmentacion_tamano_1",
    "segmentacion_tamano_2",
}

# variables que vienen logadas en tu pipeline (mismo nombre)
LOGGED_IN_MODEL = {"rotacion_stocks", "ingresos_de_explotacion"}
